### ISSUE TITLE
node 11.1.0 onStreamRead params have changed

### ISSUE THREAD

**Issue by daviddias** [indutny/handle-thing#6]
Keeping track of https://github.com/spdy-http2/handle-thing/pull/5#issue-229119787

**Comment by jakubzitny** [comment]
Any update on this? It's still happening in Node 12.8.

**Comment by pedrokarim** [comment]
I had this problem (see [issue #363](https://github.com/spdy-http2/node-spdy/issues/363)) using node-spdy, I just reversed the parameter order of the function `.onread` for` onStreamRead` in `internal / stream_base_commons.js` but I had to change the `handle-thing` package to test. Now it works as before. (excuse me, my english is bad 😅)

![handle-thing_file_handle-new](https://user-images.githubusercontent.com/28218643/67862138-dd7d9c00-fb21-11e9-8590-8a28e736c56f.PNG)

<u>Error encountered :</u>
```
internal/buffer.js:788
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:788:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:153:17)
    at Stream.<anonymous> (C:\Users\xxx\Desktop\xxx\node_modules\handle-thing\lib\handle.js:88:10)
    at Stream.emit (events.js:198:15)
    at endReadableNT (C:\Users\xxx\Desktop\xxx\node_modules\spdy-transport\node_modules\readable-stream\lib\_stream_readable.js:1077:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by pecet86** [comment]
**Possible solution**

add:
```js
const NODE_MAJOR_VERSION = +process.versions.node.split('.')[0];
```

```js
Handle.prototype._flow = function flow () {
  var self = this
  this._stream.on('data', function (chunk) {
		if (NODE_MAJOR_VERSION < 11) {
			self.onread(chunk.length, chunk)
		} else {
			self.onread(chunk)
		}
  })

  this._stream.on('end', function () {
		if (NODE_MAJOR_VERSION < 11) {
			self.onread(uv.UV_EOF, Buffer.alloc(0))
		} else {
			self.onread(Buffer.alloc(0))
		}
  })

  this._stream.on('close', function () {
    setImmediate(function () {
      if (self._reading) {
				if (NODE_MAJOR_VERSION < 11) {
					self.onread(uv.UV_ECONNRESET, Buffer.alloc(0))
				} else {
					self.onread(Buffer.alloc(0))
				}
      }
    })
  })
}
```

also works with versions <11 and> = 11
